FROM python:3.13-slim
WORKDIR /work
COPY main.c Makefile ./
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    gcc make libc6-dev && \
    rm -rf /var/lib/apt/lists/*
RUN make
CMD ["./hello"]
